### ISSUE TITLE
Formadable dpreciated.php has changed and breaks functions

### ISSUE THREAD

**Issue by bennnyuk** [TrevorMills/formidable-plus#2]
In formidbale Pro (since version 2.03.06) , depreicated.php has changed from

$frmdb              = new FrmDb();
$frm_field          = new FrmField();
$frm_form           = new FrmForm();
$frm_entry          = new FrmEntry();
$frm_entry_meta     = new FrmEntryMeta();

to

$frmdb             = new FrmDbDeprecated();
$frm_field          = new FrmFieldDeprecated();
$frm_form           = new FrmFormDeprecated();
$frm_entry          = new FrmEntryDeprecated();
$frm_entry_meta     = new FrmEntryMetaDeprecated();

results in multiple errors and form nots working.

AH01071: Got error 'PHP message: PHP Fatal error: Call to undefined method FrmFieldDeprecated::getIds() in /var/www/vhosts/site1/httpdocs/wp-content/plugins/formidable-plus/classes/helpers/FrmPlusEntryMetaHelper.php on line 482\n', referer: https://www.site1.com/page-with-form-on

**Comment by TrevorMills** [comment]
I hope to get a chance to look into this.  Shouldn't take too long to get a fix together.  No promises though.  This is not in active development.

If you're dev, I believe the fix is to change:

`$frm_field->getIds();`

to

`FrmField::getIds();`

**Comment by jehzlau** [comment]
Yeah. Same issue here. Doesn't appear always. Sometimes the depreciated issue is shown, sometimes it doesn't show. Anyway, the form is still saved regardless of the php fatal error. :D

**Comment by TrevorMills** [comment]
Hello.  

Formidable Plus should be working now with the latest Formidable Pro.

**Comment by jehzlau** [comment]
Wow awesome!!!!
Sent securely using a decentralized application on the Ethereum blockchain

-----Original Message-----
